# Generated by Django 5.1.1 on 2024-10-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotresponse',
            name='user_query',
            field=models.CharField(max_length=255),
        ),
    ]
