# Generated by Django 5.1.1 on 2024-10-09 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0003_alter_chatbotresponse_user_query'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('Feature Request', 'Feature Request'), ('Bug Report', 'Bug Report'), ('General Feedback', 'General Feedback')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
