# Generated by Django 5.1.1 on 2024-11-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0008_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
