# Generated by Django 5.1.1 on 2024-10-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0009_chathistorymessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='image',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='exterrior_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='interrior_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
