# Generated by Django 5.1.1 on 2024-10-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0010_remove_propertyimage_image_and_more'),
        ('USERS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_block_no',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_house_no',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], unique=True),
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_full_name', models.CharField(max_length=255)),
                ('visitor_relation', models.CharField(max_length=100)),
                ('visit_date', models.DateTimeField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERS.homeowner')),
            ],
        ),
    ]
