# Generated by Django 5.1.1 on 2024-10-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0011_alter_property_property_block_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
