# Generated by Django 5.1.1 on 2024-10-09 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOMEOWNER', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance_request',
            name='date_requested',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 10, 9, 12, 12, 25, 243886, tzinfo=datetime.timezone.utc)),
        ),
    ]
