# Generated by Django 5.1.1 on 2024-10-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOMEOWNER', '0002_alter_maintenance_request_date_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance_request',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
