# Generated by Django 5.1.1 on 2024-10-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOMEOWNER', '0003_alter_maintenance_request_date_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance_request',
            name='date_resolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
