# Generated by Django 5.1.1 on 2024-10-28 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOMEOWNER', '0004_maintenance_request_date_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notif_url',
        ),
        migrations.AlterField(
            model_name='notification',
            name='maintenance_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HOMEOWNER.maintenance_request'),
        ),
    ]
