# Generated by Django 5.1.1 on 2024-10-28 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0011_alter_property_property_block_no_and_more'),
        ('HOMEOWNER', '0005_remove_notification_notif_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='visit_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ADMIN.visitrequest'),
        ),
    ]
