from django.contrib import admin
from . import views
from django.urls import path

urlpatterns = [
	path('check-auth-status/', views.check_auth_status, name='check_auth_status'),
    path('admin dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('maintenance_requests_data/', views.maintenance_requests_data, name='maintenance_requests_data'),
    path('homeowners/', views.homeowners, name='homeowners'),
	# path('filter_properties/', views.filter_properties, name='filter_properties'),
	path('admin_owner_profile/<int:pk>/', views.admin_owner_profile, name='admin_owner_profile'),
	path('delete_all_homeowners/', views.delete_all_homeowners, name='delete_all_homeowners'),
    path('secretaries/', views.secretaries, name='secretaries'),
	path('new_secretary/', views.new_secretary, name='new_secretary'),
	path('delete_all_secretaries/', views.delete_all_secretaries, name='delete_all_secretaries'),
    path('residents/', views.residents, name='residents'),
	path('delete_resident/<int:pk>', views.delete_resident, name='delete_resident'),
	path('edit_resident/<int:pk>/', views.edit_resident, name='edit_resident'),
	path('new_resident/', views.new_resident, name='new_resident'),
    path('pending_accounts/', views.pending_accounts, name='pending_accounts'),
    path('admin_get_pending_registrations/', views.admin_get_pending_registrations, name='admin_get_pending_registrations'),
    path('admin_mark_messages_as_read/', views.admin_mark_messages_as_read, name='admin_mark_messages_as_read'),
    path('admin_messages/', views.admin_messages, name='admin_messages'),
    path('acceptPending/<int:pk>/', views.acceptPending, name='acceptPending'),
	path('deny_pending/<int:pk>/', views.deny_pending, name='deny_pending'),
    path('new secretary/', views.new_secretary, name='new_secretary'),
    path('new_homeowner/', views.new_homeowner, name='new_homeowner'),
    path('delete_owner/<int:pk>/', views.delete_owner, name='delete_owner'),
    path('delete_secretary/<int:pk>/', views.delete_secretary, name='delete_secretary'),
    path('edit_owner/<int:pk>/', views.edit_owner, name='edit_owner'),
    path('edit_secretary/<int:pk>/', views.edit_secretary, name='edit_secretary'),
    path('maintenance_request_list/', views.maintenance_request_list, name='maintenance_request_list'),
	path('admin_maintenance_personnel_list/', views.admin_maintenance_personnel_list, name='admin_maintenance_personnel_list'),
    path('admin_delete_all_repairman/', views.admin_delete_all_repairman, name='admin_delete_all_repairman'),
	path('admin_add_repairman/', views.admin_add_repairman, name='admin_add_repairman'),
	path('assign_request/', views.assign_request, name='assign_request'),
    # path('change_to_onGoing/<int:pk>/', views.change_to_onGoing, name='change_to_onGoing'),
    path('change_to_done/<int:pk>/', views.change_to_done, name='change_to_done'),
    path('events/', views.events, name='events'),
    path('events/', views.get_events, name='get_events'),
	path('edit_event/<int:pk>/', views.edit_event, name='edit_event'),
	path('delete_event/<int:pk>/', views.delete_event, name='delete_event'),
    path('event_detail/<int:pk>/', views.event_detail, name='event_detail'),
	path('admin_announcements/', views.admin_announcements, name='admin_announcements'),
	path('admin_edit_announcement/<int:pk>/', views.admin_edit_announcement, name='admin_edit_announcement'),
	path('admin_delete_announcement/<int:pk>/', views.admin_delete_announcement, name='admin_delete_announcement'),
    path('admin_announcement_comment/<int:pk>/', views.admin_announcement_comment, name='admin_announcement_comment'),
    path('properties/', views.properties, name='properties'),
    path('upload_property_images/<int:pk>/', views.upload_property_images, name='upload_property_images'),
    path('get_property_images/<int:property_id>/', views.get_property_images, name='get_property_images'),
    path('admin_property_detail/<int:pk>/', views.admin_property_detail, name='admin_property_detail'),
    path('properties/<int:property_id>/images/', views.get_property_images, name='get_property_images'),
    path('edit_property/<int:pk>/', views.edit_property, name='edit_property'),
    path('delete_property/<int:pk>/', views.delete_property, name='delete_property'),
	path('delete_all_properties/', views.delete_all_properties, name='delete_all_properties'),
    path('admin_messages/', views.admin_messages, name='admin_messages'),
    path('admin_get_new_messages/', views.admin_get_new_messages, name='admin_get_new_messages'),
    # path('add_property/', views.add_property, name='add_property'),
    path('admin_unread_notifications_count/', views.admin_unread_notifications_count, name='admin_unread_notifications_count'),
    path('admin_notifications/', views.admin_notifications, name='admin_notifications'),
	path('admin_mark_single_notification_as_read/<int:notification_id>/', views.admin_mark_single_notification_as_read, name='admin_mark_single_notification_as_read'),
    path('mark_notifications_as_read/', views.mark_notifications_as_read, name='mark_notifications_as_read'),
	path('admin_logs/', views.admin_logs, name='admin_logs'),
	path('admin_payment_reminder/<int:pk>/', views.admin_payment_reminder, name='admin_payment_reminder'),
    path('submit_chatFeedback/<int:conversation_id>/', views.submit_chatFeedback, name='submit_chatFeedback'),
    path('chat/history/', views.get_chat_history, name='get_chat_history'),
    path('save-feedback/', views.save_feedback, name='save_feedback'),
]






