const responses = {
    'hello': 'Hello! How can I help you today?',
    'hi': 'Hello! How can I help you today?',
    'thanks': "You're welcome! Is there anything else I can help you with?",
    'thank you': "You're welcome! Is there anything else I can help you with?",
    'thank': "You're welcome! Is there anything else I can help you with?",
    'thankyou': "You're welcome! Is there anything else I can help you with?",
    'are you': "I am just a chatbot created by the creator of the system. Just let me know if there's something I can assist you with.",
    'sorry': "It's okay!",
    'none': "Okay, just let me know if there's anything I can assist you with.",
    'no': "Okay, just let me know if there's anything I can assist you with.",
    'nothing': "Okay, just let me know if there's anything I can assist you with.",
    'ok': "Just let me know if there's anything I can assist you with.",
    'add household member': "To add a household member, look through the sidebar in your dashboard, then click the 'Add Member' button.",
    'housing management?': "The housing management system is a platform designed to help manage and allocate housing for families in need.",
    'use system?': "The system is designed for homeowners, secretaries, and administrators involved in managing the housing management.",
    'assistance available homeowners?': "Assistance includes temporary housing, financial aid for repairs, access to support services, and guidance on rebuilding and recovery processes.",
    'request report maintenance': "If you want to report or request maintenance, look to the sidebar and click the 'Request Maintenance' button, then fill out the information about the damage.",
    'housing free no fee pay much': "This housing program is free and sponsored by the government.",
    'change profile picture': "To change your profile picture, look through the upper right side and click on your photo.",
    'much household i': 'Based on your record, you have ',
    // Added 100 Prompts
    'how are you?': "I’m doing great! How about you?",
    "how's your day?": "I’m here 24/7, so every day is the same. How's yours?",
    'what’s your name?': "I’m just your friendly system chatbot! How can I assist you?",
    'what can you do?': "I can help you with information about our system, guide you through different features, and more!",
    'do you like talking?': "I’m programmed to talk and assist you, so yes, I enjoy it!",
    'what’s the time?': "I don’t keep track of time, but your device can help with that.",
    'what’s your job?': "My job is to assist users in navigating this housing management system.",
    'how old are you?': "I don’t age, but I was built to last and help you anytime!",
    'where do you live?': "I live in the cloud, always accessible for you!",
    'do you have any hobbies?': "Helping you out is my main hobby!",
    'can you help me?': "Of course! What do you need help with?",
    'where’s the support button?': "You can find the support button in the dashboard or navigation bar.",
    'can you dance?': "I can’t dance, but I can guide you through some steps if you’d like!",
    'tell me a joke': "Why did the computer go to therapy? It had too many bugs!",
    'do you have friends?': "You’re my friend! I interact with lots of users like you.",
    'what’s your favorite food?': "I don’t eat, but I bet food sounds good right now. What’s yours?",
    'do you sleep?': "I don’t need sleep. I’m always here when you need me!",
    'can you sing?': "I can’t sing, but I’d be happy to chat with you instead!",
    'what’s your favorite movie?': "I don't watch movies, but I'd love to hear about yours!",
    'do you like animals?': "I think animals are fascinating! Do you have any pets?",
    'can you help me find my profile?': "Sure! Look in the top-right corner of your screen to access your profile.",
    'who built you?': "I was built by the developers behind this housing management system!",
    'what’s your purpose?': "I’m here to make your experience with the system as smooth as possible.",
    'how’s the system today?': "The system is working perfectly! How can I assist you today?",
    'what should I do next?': "If you’re not sure, you can check the menu for options or ask me for help!",
    'can you read?': "Yes, I can process and understand your messages.",
    'how do I delete my account?': "Please contact support to help with account deletion.",
    'can you schedule an appointment for me?': "I can guide you through the steps to schedule one using the system.",
    'can you translate?': "I’m not a full translator, but I can help with some basic phrases.",
    'do you have emotions?': "I don't have emotions, but I'm always here to assist with a positive attitude!",
    'what should I do if I forget my password?': "If you forget your password, click the 'Forgot Password' link on the login page.",
    'how do I reset my password?': "You can reset your password through the 'Forgot Password' link in the login section.",
    'who’s the admin?': "The admin is responsible for managing system users and features.",
    'how do I request a visit?': "Click the 'Request Visit' button in the block you're interested in on the route map.",
    'do you know me?': "I don’t have memories, but I’m always ready to help!",
    'how can I request maintenance?': "Go to the sidebar, click 'Request Maintenance', and fill out the form.",
    'how many users are there?': "I don’t track other users, but the system admin might have that info.",
    'where is the Pope Francis Village?': "It’s located in Tacloban City. You can explore it on the route map!",
    'what is a chatbot?': "A chatbot is a program designed to simulate conversation with users.",
    'who owns this system?': "The system is maintained by the Beta Bayview Homes Subdivision administration.",
    'do you know how to fix errors?': "I can provide guidance, but more technical errors are better handled by the support team.",
    'what’s the next event?': "Check the 'View Events' tab for the upcoming events.",
    'how do I update my profile?': "Click on your profile picture in the top-right corner to update your details.",
    'how do I log out?': "Look for the 'Logout' button in the menu or profile dropdown.",
    'how do I view my properties?': "Click on 'Manage Properties' in the dashboard to see your assigned properties.",
    'can I message other users?': "Yes! Use the messaging feature in your dashboard.",
    'what happens if my property is under maintenance?': "You’ll receive a notification and updates about the maintenance progress.",
    'can I attend events?': "Yes, events are open to homeowners. Check the 'Events' section for more details.",
    'how do I manage household members?': "Go to your dashboard, then click 'Manage Members' to add, remove, or edit members.",
    'do I have notifications?': "Click the bell icon in the top-right corner to view your notifications.",
    'is the system safe?': "Yes, the system is designed with security in mind to protect user data.",
    'how can I become a homeowner?': "You can apply through the secretary, or if eligible, request a property assignment.",
    'what’s my role in the system?': "You are a homeowner. You can manage your household, properties, and more!",
    'do you have a tutorial?': "You can find a user guide or tutorial in the 'Help' section of the dashboard.",
    'can I customize my dashboard?': "Customization options may vary, but feel free to explore the settings.",
    'do I need to pay anything?': "This program is free, sponsored by the government.",
    'how do I contact support?': "Click the 'Support' button in the menu or footer to reach out to the support team.",
    'what’s the purpose of the route map?': "The route map helps visitors find their way through the community and request visits.",
    'how do I invite someone to visit?': "Go to the 'Request Visit' feature in your dashboard and invite visitors to your block.",
    'can I view announcements?': "Yes, click the 'Announcements' tab in your dashboard to stay updated.",
    'what do I do if I see an error?': "Please report any errors using the 'Support' button or contact the admin.",
    'how do I delete a household member?': "Go to 'Manage Members' in your dashboard and select the member you wish to delete.",
    'can I view past events?': "Yes, the events section in your dashboard lists both past and upcoming events.",
    'what if I need help outside of the system?': "For external assistance, reach out to community services or your secretary.",
    'what happens if I lose access to my account?': "Click 'Forgot Password' or contact support for help regaining access.",
    'who can help with property issues?': "You can report property issues using the 'Request Maintenance' button in the sidebar.",
};
