from django.contrib import admin
from . import views
from django.urls import path

urlpatterns = [
	path('check-auth-status/', views.check_auth_status, name='check_auth_status'),
    path('secretary_dashbord/', views.secretary_dashboard, name='secretary_dashboard'),
    path('sec_homewowners/', views.sec_homeowners, name='sec_homeowners'),
	path('sec_owner_profile/<int:pk>', views.sec_owner_profile, name='sec_owner_profile'),
	path('sec_edit_owner/<int:pk>', views.sec_edit_owner, name='sec_edit_owner'),
	path('sec_homeowner_detail/<int:pk>/', views.sec_homeowner_detail, name='sec_homeowner_detail'),
	path('sec_payment_reminder/<int:pk>/', views.sec_payment_reminder, name='sec_payment_reminder'),
	path('sec_new_homeowner/', views.sec_new_homeowner, name='sec_new_homeowner'),
	path('sec_properties/', views.sec_properties, name='sec_properties'),
	path('sec_property_detail/<int:pk>/', views.sec_property_detail, name='sec_property_detail'),
	path('properties/<int:pk>/upload-images/', views.upload_property_images, name='upload_property_images'),
    path('properties/<int:property_id>/images/', views.get_property_images, name='get_property_images'),
	path('sec_edit_property/<int:pk>', views.sec_edit_property, name='sec_edit_property'),
	path('sec_delete_property/<int:pk>', views.sec_delete_property, name='sec_delete_property'),
	path('sec_delete_event/<int:pk>', views.sec_delete_event, name='sec_delete_event'),
	path('sec_delete_owner/<int:pk>', views.sec_delete_owner, name='sec_delete_owner'),
	# path('sec_add_property/', views.sec_add_property, name='sec_add_property'),
	path('sec_maintenance_request_list/', views.sec_maintenance_request_list, name='sec_maintenance_request_list'),
	path('sec_maintenance_personnel_list/', views.sec_maintenance_personnel_list, name='sec_maintenance_personnel_list'),
	path('sec_assign_request/', views.sec_assign_request, name='sec_assign_request'),
    path('sec_delete_all_repairman/', views.sec_delete_all_repairman, name='sec_delete_all_repairman'),
	path('sec_add_repairman/', views.sec_add_repairman, name='sec_add_repairman'),
    path('sec_get_maintenances/', views.sec_get_maintenances, name='sec_get_maintenances'),
	path('sec_change_to_done/<int:pk>', views.sec_change_to_done, name='sec_change_to_done'),
	# path('sec_change_to_onGoing/<int:pk>', views.sec_change_to_onGoing, name='sec_change_to_onGoing'),
	path('sec_residents/', views.sec_residents, name='sec_residents'),
	path('sec_new_resident/', views.sec_new_resident, name='sec_new_resident'),
	path('sec_edit_resident/<int:pk>', views.sec_edit_resident, name='sec_edit_resident'),
	path('sec_delete_resident/<int:pk>', views.sec_delete_resident, name='sec_delete_resident'),
	path('sec_pending_accounts/', views.sec_pending_accounts, name='sec_pending_accounts'),
	path('get_pending_registrations/', views.get_pending_registrations, name='get_pending_registrations'),
	path('sec_acceptPending/<int:pk>', views.sec_acceptPending, name='sec_acceptPending'),
	path('sec_deny_pending/<int:pk>', views.sec_deny_pending, name='sec_deny_pending'),
	path('sec_events/', views.sec_events, name='sec_events'),
	path('sec_announcements/', views.sec_announcements, name='sec_announcements'),
	path('sec_edit_announcement/<int:pk>/', views.sec_edit_announcement, name='sec_edit_announcement'),
	path('sec_delete_announcement/<int:pk>/', views.sec_delete_announcement, name='sec_delete_announcement'),
	path('sec_announcement_comment/<int:pk>/', views.sec_announcement_comment, name='sec_announcement_comment'),
	path('sec_maintenance_requests_data/', views.sec_maintenance_requests_data, name='sec_maintenance_requests_data'),
	path('sec_edit_event/<int:pk>/', views.sec_edit_event, name='sec_edit_event'),
	path('sec_event_detail/<int:pk>/', views.sec_event_detail, name='sec_event_detail'),
    path('sec_messages/', views.sec_messages, name='sec_messages'),
	path('sec_notifications/', views.sec_notifications, name='sec_notifications'),
	path('unread_notifications_count/', views.unread_notifications_count, name='unread_notifications_count'),
	path('sec_mark_notifications_as_read/', views.sec_mark_notifications_as_read, name='sec_mark_notifications_as_read'),
	path('sec_mark_single_notification_as_read/<int:notification_id>/', views.sec_mark_single_notification_as_read, name='sec_mark_single_notification_as_read'),	
]



